export const FECTH_POSTS_REQUEST= 'post/FECTH_POSTS_REQUEST';
export const FECTH_POSTS_SUCCESS= 'post/FECTH_POSTS_SUCCESS';
export const FECTH_POSTS_FAILURE= 'post/FECTH_POSTS_FAILURE';

export const DELETE_POST_REQUEST= 'post/DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS= 'post/DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE= 'post/DELETE_POST_FAILURE';